# Generated by Django 2.2.7 on 2019-11-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zainteresowania_uzytkownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_zainteresowania', models.IntegerField()),
                ('Zainteresowanie', models.CharField(max_length=45)),
                ('ID_uzytkownika', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dane_uzytkownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie_uzytkownika', models.CharField(max_length=200)),
                ('Wiek', models.IntegerField()),
                ('Miejscowosc', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('ID_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.zainteresowania_uzytkownika')),
            ],
        ),
    ]
